/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as productivityTasksIndexRouteImport } from './routes/(productivity)/tasks/index'
import { Route as productivityNotesIndexRouteImport } from './routes/(productivity)/notes/index'
import { Route as financeEmiIndexRouteImport } from './routes/(finance)/emi/index'
import { Route as financeEmiTaxIndexRouteImport } from './routes/(finance)/emi/tax/index'
import { Route as financeEmiSimpleIndexRouteImport } from './routes/(finance)/emi/simple/index'
import { Route as financeEmiCompareLoansIndexRouteImport } from './routes/(finance)/emi/compare-loans/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const productivityTasksIndexRoute = productivityTasksIndexRouteImport.update({
  id: '/(productivity)/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const productivityNotesIndexRoute = productivityNotesIndexRouteImport.update({
  id: '/(productivity)/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const financeEmiIndexRoute = financeEmiIndexRouteImport.update({
  id: '/(finance)/emi/',
  path: '/emi/',
  getParentRoute: () => rootRouteImport,
} as any)
const financeEmiTaxIndexRoute = financeEmiTaxIndexRouteImport.update({
  id: '/(finance)/emi/tax/',
  path: '/emi/tax/',
  getParentRoute: () => rootRouteImport,
} as any)
const financeEmiSimpleIndexRoute = financeEmiSimpleIndexRouteImport.update({
  id: '/(finance)/emi/simple/',
  path: '/emi/simple/',
  getParentRoute: () => rootRouteImport,
} as any)
const financeEmiCompareLoansIndexRoute =
  financeEmiCompareLoansIndexRouteImport.update({
    id: '/(finance)/emi/compare-loans/',
    path: '/emi/compare-loans/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/emi': typeof financeEmiIndexRoute
  '/notes': typeof productivityNotesIndexRoute
  '/tasks': typeof productivityTasksIndexRoute
  '/emi/compare-loans': typeof financeEmiCompareLoansIndexRoute
  '/emi/simple': typeof financeEmiSimpleIndexRoute
  '/emi/tax': typeof financeEmiTaxIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/emi': typeof financeEmiIndexRoute
  '/notes': typeof productivityNotesIndexRoute
  '/tasks': typeof productivityTasksIndexRoute
  '/emi/compare-loans': typeof financeEmiCompareLoansIndexRoute
  '/emi/simple': typeof financeEmiSimpleIndexRoute
  '/emi/tax': typeof financeEmiTaxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(finance)/emi/': typeof financeEmiIndexRoute
  '/(productivity)/notes/': typeof productivityNotesIndexRoute
  '/(productivity)/tasks/': typeof productivityTasksIndexRoute
  '/(finance)/emi/compare-loans/': typeof financeEmiCompareLoansIndexRoute
  '/(finance)/emi/simple/': typeof financeEmiSimpleIndexRoute
  '/(finance)/emi/tax/': typeof financeEmiTaxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/emi'
    | '/notes'
    | '/tasks'
    | '/emi/compare-loans'
    | '/emi/simple'
    | '/emi/tax'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/emi'
    | '/notes'
    | '/tasks'
    | '/emi/compare-loans'
    | '/emi/simple'
    | '/emi/tax'
  id:
    | '__root__'
    | '/'
    | '/(finance)/emi/'
    | '/(productivity)/notes/'
    | '/(productivity)/tasks/'
    | '/(finance)/emi/compare-loans/'
    | '/(finance)/emi/simple/'
    | '/(finance)/emi/tax/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  financeEmiIndexRoute: typeof financeEmiIndexRoute
  productivityNotesIndexRoute: typeof productivityNotesIndexRoute
  productivityTasksIndexRoute: typeof productivityTasksIndexRoute
  financeEmiCompareLoansIndexRoute: typeof financeEmiCompareLoansIndexRoute
  financeEmiSimpleIndexRoute: typeof financeEmiSimpleIndexRoute
  financeEmiTaxIndexRoute: typeof financeEmiTaxIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(productivity)/tasks/': {
      id: '/(productivity)/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof productivityTasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(productivity)/notes/': {
      id: '/(productivity)/notes/'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof productivityNotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(finance)/emi/': {
      id: '/(finance)/emi/'
      path: '/emi'
      fullPath: '/emi'
      preLoaderRoute: typeof financeEmiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(finance)/emi/tax/': {
      id: '/(finance)/emi/tax/'
      path: '/emi/tax'
      fullPath: '/emi/tax'
      preLoaderRoute: typeof financeEmiTaxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(finance)/emi/simple/': {
      id: '/(finance)/emi/simple/'
      path: '/emi/simple'
      fullPath: '/emi/simple'
      preLoaderRoute: typeof financeEmiSimpleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(finance)/emi/compare-loans/': {
      id: '/(finance)/emi/compare-loans/'
      path: '/emi/compare-loans'
      fullPath: '/emi/compare-loans'
      preLoaderRoute: typeof financeEmiCompareLoansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  financeEmiIndexRoute: financeEmiIndexRoute,
  productivityNotesIndexRoute: productivityNotesIndexRoute,
  productivityTasksIndexRoute: productivityTasksIndexRoute,
  financeEmiCompareLoansIndexRoute: financeEmiCompareLoansIndexRoute,
  financeEmiSimpleIndexRoute: financeEmiSimpleIndexRoute,
  financeEmiTaxIndexRoute: financeEmiTaxIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
